### ISSUE TITLE
spectral_normalization_nondiff.py

### ISSUE THREAD

**Issue by hellopipu** [christiancosgrove/pytorch-spectral-normalization-gan#16]
Thanks for your code . I'm quite confused with the nondiff version, what does it for , and what's the difference with the diff version. Thanks

**Comment by christiancosgrove** [comment]
nondiff stands for nondifferentiable. Rather than creating a new tensor to represent the normalized weights (which is what the other version does), the nondiff version simply replaces w with a normalized weight matrix.

In my experiments (long time ago) I found there wasn’t much of a difference between these two implementations.
